name: android
description: "dalathasfarm project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  decimal: ^3.0.0
  http: ^0.13.6
  email_validator: ^3.0.0
  url_launcher: ^6.1.11
  mime: ^1.0.0
  image_picker: ^0.8.7+4
  http_parser: ^4.0.0
  intl: ^0.20.2
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
