server:
  port: 8080

spring:
  application:
    name: dalathasfarm
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/dalathasfarm}
    username: root
    password: ${MYSQL_ROOT_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

api:
  prefix: /api/v1

jwt:
  expiration: 2592000 #30 days = 30d * 24h * 60m * 60s
  expiration-refresh-token: 5184000 #60 days = 60d * 24h * 60m * 60s
  secretKey: k91v0UiqsELb5S9c14/gtKvcs/gxCnD8CBXJHj41WlE=

# health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: "health, info"

vnpay:
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-web-url: "${VNPAY_RETURN_URI:http://localhost:8080/api/v1/payments/payment-callback}"
#  return-mobile-url: "${VNPAY_RETURN_URI:http://192.168.1.68:8080/api/v1/payments/payment-callback}"
#  return-mobile-url: "${VNPAY_RETURN_URI:http://172.17.1.216:8080/api/v1/payments/payment-callback}"
  return-mobile-url: "${VNPAY_RETURN_URI:http://172.17.26.111:8080/api/v1/payments/payment-callback}"
  #  Tài khoản VNPay deploy
  tmn-code: "OZYHVEZ5"
  secret-key: "O9G96CAW41KRP6YKLVNKA9W04L0B7XEN"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"

ollama:
  base-url: http://localhost:11434
  model: ${OLLAMA_MODEL:qwen2.5:7b}